In [1]:
import numpy as np

In [26]:
#Data Type - Numpy

numpy_1 = np.array([1,4,3])
numpy_2 = np.array([[1,4,3],[9,2,7]])
print(numpy_1)
print(numpy_2)

print(numpy_2.shape)                      #dimension
print(numpy_2.size)                       #number array

numpy_3 = np.arange(1,2000, 1)            #1 to 1999 with increment of 1
print(numpy_3)

numpy_4 = np.arange(0.5,3,0.5)            #0.5 to 2.5 with increment of 0.5
print(numpy_4)

numpy_5 = np.arange(1,5,)                 #1 to 5 with increment of 1
print(numpy_5)

numpy_6 = np.linspace(3,9,10)             #3 to 9, divide into 10 numbers
print(numpy_6)

[1 4 3]
[[1 4 3]
 [9 2 7]]
(2, 3)
6
[   1    2    3 ... 1997 1998 1999]
[0.5 1.  1.5 2.  2.5]
[1 2 3 4]
[3.         3.66666667 4.33333333 5.         5.66666667 6.33333333
 7.         7.66666667 8.33333333 9.        ]


In [27]:
##Numpy Array Usage


print(numpy_1[1])                         #second element

print(numpy_1[1:])                        #second element to end

print(numpy_1[-1])                        #last element                   

print(numpy_2[0,1])                       #first array, second element

print(numpy_2[:,-1])                      #last column; all arrays, last element

print(numpy_2[:,[0,2]])                   #all arrays; first and third element

print(np.zeros((3,5)))                    #3x5 zero matrix

print(np.ones((5,3)))                     #5x3 ones matrix

4
[4 3]
3
4
[3 7]
[[1 3]
 [9 7]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
##Numpy Array Operations

numpy_7 = np.array([[1,2],[3,4]])
numpy_8 = np.array([[3,4],[5,6]])
print(numpy_7)
print(numpy_8)

print(numpy_7 + 2)

print(numpy_7 ** 2)

print(numpy_7 + numpy_8)

print(numpy_7 * numpy_8)

print(numpy_7 ** numpy_8)

print(numpy_7.T)

numpy_9 = np.array([1,4,9,16])
print(np.sqrt(numpy_9))



[[1 2]
 [3 4]]
[[3 4]
 [5 6]]
[[3 4]
 [5 6]]
[[ 1  4]
 [ 9 16]]
[[ 4  6]
 [ 8 10]]
[[ 3  8]
 [15 24]]
[[   1   16]
 [ 243 4096]]
[[1 3]
 [2 4]]
[1. 2. 3. 4.]


In [41]:
 #If-Else Statements


###Example #1
x = 3

if x > 1 and x < 2:
    y = 2
elif x > 2 and x < 4:
    y = 4
else:
    y = 0

print(y)

###Example #2
is_Student = True

if is_Student:
    person = 'student'
else:
    person = 'not student'

print(person)

###Example #3 with Ternary operator
person = 'student' if is_Student else 'not student'
print(person)

4
student
student


In [48]:
#For Loops

###Example #1
n = 0

for i in range(1,4):
    n = n + i

print(n)

###Example #2

for c in "banana":
    print(c)


###Example #3

s = 'banana'
for i in range(len(s)):
    print(s[i])

###Example #4
dict_a = {"One": 1, "Two": 2, "Three": 3}

for key in dict_a.keys():                   #Looping through dictionary with keys
    print(key, dict_a[key])

###Example #5
for key, value in dict_a.items():           #Looping through dictionary with values
    print(key, value)

###Example #6
a = ["One", "Two", "Three"]
b = [1,2,3]

for i, j in zip(a,b):

6
b
a
n
a
n
a
b
a
n
a
n
a
One 1
Two 2
Three 3
One 1
Two 2
Three 3
