In [3]:
import numpy as np
vectorRow = np.array([[1,-5,3,2,4]])                #2 brackets because need to define row or vector
vectorColumn = np.array([[1],[2],[3],[4]])
print(vectorRow.shape)
print(vectorColumn.shape)

(1, 5)
(4, 1)


In [7]:
from numpy.linalg import norm

newVector = vectorRow.T                     #transpose, change numbers with columns
print(newVector)

norm1 = norm(newVector,1)                   #taxicab norm
norm2 = norm(newVector, 2)                  #p norm
normInf = norm(newVector, np.inf)           #inf = infinity

print('L1 is: %.1f'%norm1)
print('L2 is: %.1f'%norm2)
print('L3 is: %.1f'%normInf)


[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L1 is: 15.0
L2 is: 7.4
L3 is: 5.0


In [9]:
from numpy import arccos, dot

#dot product
v = np.array([[10,9,3]])
w = np.array([[2,5,12]])
theta = arccos(dot(v,w.T)/(norm(v) * norm(w)))

print(theta)

#cross product
v = np.array([[0,2,0]])
w = np.array([[3,0,0]])

print(np.cross(v,w))




[[0.97992471]]
[[ 0  0 -6]]


In [12]:
#matrices
p = np.array([[1,7], [2,3], [5,0]])
q = np.array([[2,6,3,1], [1,2,3,4]])
print(p)
print(q)
print(np.dot(p,q))
np.dot(q,p)                             #of course error, because the size of the matrices dont match

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [14]:
#determinants
#Laplace Expansion                  O(n!); therefore, inefficient               -> if 5x5 matrix, then O(5!)
from numpy.linalg import det

m = np.array([[0,2,1,3], [3,2,8,1], [1,0,0,3],[0,3,2,1]])
print('M:\n', m)

print('Determinant: %.1f'%det(m))

i = np.eye(4)                       #identity matrix
print('I:\n', i)

print('M * I:\n', np.dot(m,i))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M * I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


In [15]:
#inverse of matrics
from numpy.linalg import inv
print('Inverse Matrix:\n', inv(m))

p = np.array([[0,1,0],[0,0,0],[1,0,1]])

print('Det(P):\n', det(p))

Inverse Matrix:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
Det(P):
 0.0


In [23]:
#system of linear equations
#ax = b -> x = a^-1 * b
a = np.array([[4,3,-5],[-2,-4,5],[7,8,0],[1,0,2],[9,1,-6]])
print(a)

#matrix rank
#to solve linear equations, they need to be linearly independent; if dependent, they are pretty much the same equation but multiplied with a factor
#to check if linearly independent, we can use the rank
from numpy.linalg import cond, matrix_rank
matrix_rank(a)
# 3 variables, and rank = 3; therefore can be solved

[[ 4  3 -5]
 [-2 -4  5]
 [ 7  8  0]
 [ 1  0  2]
 [ 9  1 -6]]


3