In [1]:
import numpy as np

In [26]:
#Data Type - Numpy

numpy_1 = np.array([1,4,3])
numpy_2 = np.array([[1,4,3],[9,2,7]])
print(numpy_1)
print(numpy_2)

print(numpy_2.shape)                      #dimension
print(numpy_2.size)                       #number array

numpy_3 = np.arange(1,2000, 1)            #1 to 1999 with increment of 1
print(numpy_3)

numpy_4 = np.arange(0.5,3,0.5)            #0.5 to 2.5 with increment of 0.5
print(numpy_4)

numpy_5 = np.arange(1,5,)                 #1 to 5 with increment of 1
print(numpy_5)

numpy_6 = np.linspace(3,9,10)             #3 to 9, divide into 10 numbers
print(numpy_6)

[1 4 3]
[[1 4 3]
 [9 2 7]]
(2, 3)
6
[   1    2    3 ... 1997 1998 1999]
[0.5 1.  1.5 2.  2.5]
[1 2 3 4]
[3.         3.66666667 4.33333333 5.         5.66666667 6.33333333
 7.         7.66666667 8.33333333 9.        ]


In [27]:
##Numpy Array Usage


print(numpy_1[1])                         #second element

print(numpy_1[1:])                        #second element to end

print(numpy_1[-1])                        #last element                   

print(numpy_2[0,1])                       #first array, second element

print(numpy_2[:,-1])                      #last column; all arrays, last element

print(numpy_2[:,[0,2]])                   #all arrays; first and third element

print(np.zeros((3,5)))                    #3x5 zero matrix

print(np.ones((5,3)))                     #5x3 ones matrix

4
[4 3]
3
4
[3 7]
[[1 3]
 [9 7]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
##Numpy Array Operations

numpy_7 = np.array([[1,2],[3,4]])
numpy_8 = np.array([[3,4],[5,6]])
print(numpy_7)
print(numpy_8)

print(numpy_7 + 2)

print(numpy_7 ** 2)

print(numpy_7 + numpy_8)

print(numpy_7 * numpy_8)

print(numpy_7 ** numpy_8)

print(numpy_7.T)

numpy_9 = np.array([1,4,9,16])
print(np.sqrt(numpy_9))



[[1 2]
 [3 4]]
[[3 4]
 [5 6]]
[[3 4]
 [5 6]]
[[ 1  4]
 [ 9 16]]
[[ 4  6]
 [ 8 10]]
[[ 3  8]
 [15 24]]
[[   1   16]
 [ 243 4096]]
[[1 3]
 [2 4]]
[1. 2. 3. 4.]


In [41]:
 #If-Else Statements


###Example #1
x = 3

if x > 1 and x < 2:
    y = 2
elif x > 2 and x < 4:
    y = 4
else:
    y = 0

print(y)

###Example #2
is_Student = True

if is_Student:
    person = 'student'
else:
    person = 'not student'

print(person)

###Example #3 with Ternary operator
person = 'student' if is_Student else 'not student'
print(person)

4
student
student


In [56]:
#For Loops

##Using specified Range; similar to for(;;)
n = 0

for i in range(1,4):
    n = n + i

print(n)

##Using string as range; Sort of using like foreach
for c in "banana":
    print(c)


##Using length of indices as range
s = 'banana'
for i in range(len(s)):
    print(s[i])

##Iterating through dictionary using keys; sort of like foreach
dict_a = {"One": 1, "Two": 2, "Three": 3}

for key in dict_a.keys():                   #Looping through dictionary with keys
    print(key, dict_a[key])

##Iterating through dictionary using keys and values
for key, value in dict_a.items():           #Looping through dictionary with values
                                            #use items() to use both key and value
    print(key, value)

##Iterating through 2 lists using zip function
a = ["One", "Two", "Three"]
b = [1,2,3]

for i, j in zip(a,b):                       #using zip function to combine 2 lists into tuple
    print(i,j)

##Adding all the elements in a list
s = 0
a = [2,3,1,3,3]

for i in a:
    s += i
print(s)

##Using break in for loop
for i in range(5):
    if i == 2:                              #when reaches 2, stop loop
        break
    print(i)

##Using continue in for loop
for i in range(5):
    if i == 2:
        continue                            #skip code when i == 2
    print(i)

##Using Nested For loops
x = np.array([[5,6], [7,8]])                #assign array in variable x
n, m = x.shape                              #put dimension in variables; n = x.shape[0] is row, m = x.shape[1] is column
s = 0                                       #initialize variable s; sum
for i in range(n):
    for j in range(m):                      ##adding columns first
        #print(s)
        s += x[i,j]                         #take the element with row i and column j and add

print(s)

6
b
a
n
a
n
a
b
a
n
a
n
a
One 1
Two 2
Three 3
One 1
Two 2
Three 3
One 1
Two 2
Three 3
12
0
1
0
1
3
4
26


In [60]:
#While Loop

##Determining how many times a number can be divided by 2
i = 0                   #number of iterations
n = 8                   #number

while n >= 1:
    n /= 2              #divide number by 2
    i += 1

print(f'n = {n}, i = {i}')

##Infinite loop
###Stop using ctrl + c or cmd + c
#n = 0
#while n > -1:
    #n += 1

n = 0.5, i = 4


In [73]:
#List Comprehension

##Storing number in list using for loop
y = []

for i in range(5):                  #from 0 to 4
    y.append(i ** 2)                #number squared; append to list
print(y)                            #print final list

##Storing number in list using list comprehenshion
y = [i ** 2 for i in range(5)]
print(y)

##Conditions in list comprehension
y = [i ** 2 for i in x if i%2 == 0]
print(y)

###Same as above 
z = []
for i in range(5):
    if(i%2 == 0):
        z.append(i ** 2)
print(z)

##Nested Loops using list
y = []
for i in range(5):                          #from 0 to 4
    for j in range(2):                      #from 0 to 1
        y.append(i + j)
print(y)

                                            ### 0,0 0,1 1,0 1,1 2,0 2,1 3,0 3,1, etc
##Nest loops in list comprehension                    
y = [i + j for i in range(5) for j in range(2)]
print(y)

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]
[0, 4, 16]
[0, 4, 16]
[0, 1, 1, 2, 2, 3, 3, 4, 4, 5]
[0, 1, 1, 2, 2, 3, 3, 4, 4, 5]


In [103]:
#Dictionary and Set Comprehension

##Dictionary Comprehension
x = {'a': 1, 'b': 2,'c': 3}
x = {key: v ** 3 for (key,v) in x.items()}              #??
print(x)

###Same as above
y = {'a': 1, 'b': 2,'c': 3}
for (key, v) in y.items():
   y[key] = v ** 3
print(y)

##Set Comprehension
set_a = {i * j for i in range(2) for j in range(3)}
print(set_a)

###Same as above
set_a = {}                                          #dictionary
set_a = set()                                       #make into set
for i in range(2):
    for j in range(3):
        set_a.add(i * j)

print(set_a)

{'a': 1, 'b': 8, 'c': 27}
{'a': 1, 'b': 8, 'c': 27}
{0, 1, 2}
{0, 1, 2}


In [106]:
##Square Root Program using a while loop
##? don't understand

a = 49
tol = 1e-5
e = 1
x = a/2
i = 1

while e > tol:
    y = (x + a/x)/2
    e = abs((y-x)/y)
    x = y
    print("Iteration %d: square root of %.3f = %.3f, approximate error = %.3f"%(i,a,x,e))
    i += 1

print("Square root of %f is %f"%(a,x))

Iteration 1: square root of 49.000 = 13.250, approximate error = 0.849
Iteration 2: square root of 49.000 = 8.474, approximate error = 0.564
Iteration 3: square root of 49.000 = 7.128, approximate error = 0.189
Iteration 4: square root of 49.000 = 7.001, approximate error = 0.018
Iteration 5: square root of 49.000 = 7.000, approximate error = 0.000
Iteration 6: square root of 49.000 = 7.000, approximate error = 0.000
Square root of 49.000000 is 7.000000
