In [4]:
#Question 1

#Create a list and save it in a text file that each of the item in the list will take one line.
import numpy as np
data = np.random.rand(10)

f = open('Assignment_8_1.txt', 'w')

#for i in range(len(data)):
    #f.write(str(data[i]))
    #f.write("\n")
    #or
    #f.write(str(data[i]) + ("\n"))

for i in data: 
    f.write(f"{i}\n")
f.close()

##print everything??
f = open('./Assignment_8_1.txt', 'r')
content = f.readlines()
f.close()

print(content)
#np.savetxt('Assignment_8_1.txt', data, fmt = '%.2f')

['0.5963110378508577\n', '0.859351175295493\n', '0.4483582599229702\n', '0.16933523568641484\n', '0.018255833709921676\n', '0.3394288391433403\n', '0.8138031895771609\n', '0.38449082795579714\n', '0.6116687535985963\n', '0.874009402779976\n']


In [5]:
#Question 2

array_1 = np.random.rand(5,5)                   #Create 2d nummpy array
print(array_1)
np.savetxt('Q2.csv', array_1, fmt = '%.2f', delimiter = ',', header= 'c1,c2,c3,c4,c5')

f = open('Q2.csv','r')
#to put into an array or list, need to iterate through it; readlines() allows us to put it into list, which makes indices accessible through loops
content = f.readlines()                         #put into list line by line
f.close()

data = []                               #empty array
temp = ''
for i in range(1, len(content)):
    for j in content[i]:
        print(content[i][j])
        #if content[i][j].isdigit() or content[i] == '.':

[[0.65340651 0.77324413 0.40899103 0.39769466 0.11084571]
 [0.46108744 0.4744068  0.12785537 0.00454008 0.8624204 ]
 [0.7925325  0.94206165 0.4485098  0.79536396 0.15910558]
 [0.27782369 0.41668428 0.92523173 0.0443801  0.17659366]
 [0.7840601  0.87095802 0.18788335 0.02345101 0.51296653]]


TypeError: string indices must be integers

In [1]:
#Question 3

#Save a nested list into a CSV file 
list_1 = [["A", "B", "C"], ["D", "E", "F"]]

for i in range(len(list_1)):
    for j in range(len(list_1[i])):
        f.write(str(list_1[i][j]) + ",")
        f.write("\n")
f.close()
asf
#Print it back as a 2D numpy array

NameError: name 'f' is not defined

In [2]:
#Question 4
##Save the same array in problem 2 to a pickle file and load it back

import pickle 
f2 = open('Q4.pkl', 'wb')
pickle.dump(list_1, f2)
f2.close

f3 = open('./Q4.pkl', 'rb')
my_data_1 = pickle.load(f3)
f3.close()
print(my_data_1)

EOFError: Ran out of input

In [8]:
#Question 5
##Create a dictionary and save it to a JSON file

import json

my_data_2 = {
    'firstName': ['John', 'Anna', 'Peter'], 
    'lastName': ['Doe', 'Smith', 'Jones']
}

print(my_data_2['firstName'][0]+' ' + my_data_2['lastName'][0])

f4 = open('Q5.json', 'w')
json.dump(my_data_2, f4)

John Doe


In [9]:
#Question 6
##Create a 1D numpy array and save it to a JSON file with the key named 'data'. Then load it back. 
array_2 = np.random.rand(5)
my_data_2 = {'data': list(array_2)}

f5 = open('Q6.json', 'w')
json.dump(my_data_2, f5)
f5.close()

f6 = open('./Q6.json', 'r')
my_data_3 = json.load(f6)
f6.close()
print(my_data_3['data'])

[0.7824083902672243, 0.7955538806284347, 0.982516552256808, 0.8122395349793721, 0.7713140446319796]
