In [37]:
#Assignment 2

#1
#Write a line of code that generates the following error:
#NameError: name 'x' is not defined
#print(x)

In [38]:
#3
#Assign string ‘123’ to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the type function.
S = '123'
N = float(S)

print(type(S))
print(type(N))

<class 'str'>
<class 'float'>


In [39]:
#4
#Use the print function to generate the following strings.
#	The word ‘Engineering’ has 11 letters.
#	The word ‘Book’ has 4 letters.

a = 'Engineering'
b = 11
c = 'Book'
d = 4

print(f'The word \'{a}\' has {b} letters.' )
print(f'The word \'{c}\' has {d} letters.')

The word 'Engineering' has 11 letters.
The word 'Book' has 4 letters.


In [40]:
#5
#Get the last word ‘great’ from ‘Python is great!’.

a = 'Python is great'
print(a[9:])

 great


In [41]:
#6
#Turn ‘Python is great!’ to a list.
b = list(a)
print(type(b))

<class 'list'>


In [42]:
#7
#Assign list [1, 8, 9, 15] to a variable list_a and insert 2 at index 1 using the insert method. Append 4 to the list_a using the append method.

list_a = [1,8,9,15]
list_a.insert(1,2)
list_a.append(4)
print(list_a)

[1, 2, 8, 9, 15, 4]


In [43]:
#8
#Get the unique element from (2, 3, 2, 3, 1, 2, 5).
list_b = (2,3,2,3,1,2,5)
print(set(list_b))

{1, 2, 3, 5}


In [44]:
#9
#Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Get the following:
#	union of set_a and set_b
#	intersection of set_a and set_b
#	difference of set_a to set_b
set_a = {2,3,2}
set_b = {1,2,3}

print(set_a.union(set_b))
print(set_a.intersection(set_b))
print(set_a.difference(set_b))


{1, 2, 3}
{2, 3}
set()


In [45]:
#10
#Create a dictionary that has the keys ‘A’, ‘B’, ‘C’ with values ‘a’, ‘b’, ‘c’ individually. Print all the keys in the dictionary.
dict_a = {'A':'a', 'B':'b', 'C':'c'}
print(dict_a.keys())

dict_keys(['A', 'B', 'C'])


In [46]:
#11
#Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero. Hint: Use logical expression as the index of the array.
import numpy as np
array_a = np.array([-1,0,1,2,0,3])
print(array_a[array_a > 0])

[1 2 3]


In [47]:
#12
#Create a zero array with size (2, 4) and change the 2nd column in the above array to 1.
array_c = np.zeros((2,4))
array_c[:,1] = 1
print(array_c)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [48]:
#13
#Write a cell magic to clear all the variables in the Jupyter notebook
%reset