In [24]:
#Question 1

#Create a list and save it in a text file that each of the item in the list will take one line.
import numpy as np
data = np.random.rand(10)

f = open('Assignment_8_1.txt', 'w')

#for i in range(len(data)):
    #f.write(str(data[i]))
    #f.write("\n")
    #or
    #f.write(str(data[i]) + ("\n"))

for i in data: 
    f.write(f"{i}\n")
f.close()

##print everything??
f = open('./Assignment_8_1.txt', 'r')
content = f.readlines()
f.close()

print(content)
#np.savetxt('Assignment_8_1.txt', data, fmt = '%.2f')

['0.29650279232114374\n', '0.3226755565322108\n', '0.41856736407579753\n', '0.3158636037175647\n', '0.0005463846722482124\n', '0.48090009964827884\n', '0.1160585774818722\n', '0.08051998703709573\n', '0.6341924350173526\n', '0.8947059828832228\n']


In [38]:
#Question 2

array_1 = np.random.rand(5,5)                   #Create 2d nummpy array
print(array_1)
np.savetxt('Q2.csv', array_1, fmt = '%.2f', delimiter = ',', header= 'c1,c2,c3,c4,c5')

f = open('Q2.csv','r')
#to put into an array or list, need to iterate through it; readlines() allows us to put it into list, which makes indices accessible through loops
content = f.readlines()                         #put into list line by line
f.close()

data = []                               #empty array
temp = ''
for i in range(1, len(content)):
    for j in content[i]:
        print(content[i][j])
        #if content[i][j].isdigit() or content[i] == '.':

[[0.75795121 0.36757567 0.09871107 0.67410526 0.56706081]
 [0.679944   0.92013374 0.88070148 0.34257625 0.65565684]
 [0.17691458 0.86483593 0.92080843 0.59385336 0.65054759]
 [0.8502651  0.34153369 0.88971903 0.95683389 0.1227996 ]
 [0.01066048 0.73884527 0.15211885 0.36176142 0.02546905]]


TypeError: string indices must be integers

In [22]:
#Question 3

#Save a nested list into a CSV file 
list_1 = [["A", "B", "C"], ["D", "E", "F"]]

for i in range(len(list_1)):
    for j in range(len(list_1[i])):
        f.write(str(list_1[i][j]) + ",")
        f.write("\n")
f.close()

#Print it back as a 2D numpy array