In [60]:
#Question 1

#Create a list and save it in a text file that each of the item in the list will take one line.
import numpy as np
data_1 = np.random.rand(10)

f = open('Assignment_8_1.txt', 'w')

for i in data_1: 
    f.write(f"{i}\n")
f.close()

##print everything??
f = open('./Assignment_8_1.txt', 'r')
content = f.readlines()
f.close()

print(content)

['0.2510370185036336\n', '0.3100444135336451\n', '0.13602256196148443\n', '0.8007067894618835\n', '0.7591728882514224\n', '0.4599734051992552\n', '0.31416601992096127\n', '0.44669109277919905\n', '0.5448288617829933\n', '0.9623915957593268\n']


In [61]:
#Question 2
#Save the same list in problem 1 to a CSV file.

np.savetxt('Q2.csv', data_1, fmt = '%.2f')

In [62]:
#Question #3
# Create a 2D numpy array, and save it to CSV file and read it back to a 2D array.


#getting numbers
def getNumbers(str_1):
    numbers = []
    tmp = ''

    for i in range(len(str_1)):
        #Extract numbers; any digit or point is part of the number
        if str_1[i].isdigit() or str_1[i]== '.':
            tmp += str_1[i]
        
        # Joining the obtained characters, if available, at each space or comma
        if (str_1[i]==' ' or str_1[i] == ',' or i==len(str_1)-1) and len(tmp):
            numbers.append(float(tmp))
            tmp=''
            
    return numbers


array_1 = np.random.rand(5,5)
np.savetxt('Q3.csv', array_1, fmt = '%.2f', delimiter=',', header = 'c1,c2,c3,c4,c5')

f = open('Q3.csv', 'r')
content = f.readlines()
f.close()


data = []
for i in content[1:]:
    data.append(getNumbers(i))

data = np.array(data)
print(data)


[[0.94 0.3  0.01 0.41 0.69]
 [0.45 0.17 0.32 0.04 0.26]
 [0.24 0.43 0.9  0.07 0.93]
 [0.75 0.83 0.38 0.35 0.48]
 [0.45 0.83 0.75 0.62 0.77]]


In [63]:
#Question 4
##Save the same array in problem 2 to a pickle file and load it back

import pickle 
f2 = open('Q4.pkl', 'wb')
pickle.dump(data_1, f2)
f2.close

f3 = open('./Q4.pkl', 'rb')
my_data_1 = pickle.load(f3)
f3.close()
print(my_data_1)

[0.48814992 0.76595721 0.24207278 0.68023563 0.32150273 0.20105379
 0.30066533 0.42518267 0.38191042 0.97129206]


In [8]:
#Question 5
##Create a dictionary and save it to a JSON file

import json

my_data_2 = {
    'firstName': ['John', 'Anna', 'Peter'], 
    'lastName': ['Doe', 'Smith', 'Jones']
}

print(my_data_2['firstName'][0]+' ' + my_data_2['lastName'][0])

f4 = open('Q5.json', 'w')
json.dump(my_data_2, f4)

John Doe


In [9]:
#Question 6
##Create a 1D numpy array and save it to a JSON file with the key named 'data'. Then load it back. 
array_2 = np.random.rand(5)
my_data_2 = {'data': list(array_2)}

f5 = open('Q6.json', 'w')
json.dump(my_data_2, f5)
f5.close()

f6 = open('./Q6.json', 'r')
my_data_3 = json.load(f6)
f6.close()
print(my_data_3['data'])

[0.7824083902672243, 0.7955538806284347, 0.982516552256808, 0.8122395349793721, 0.7713140446319796]
