In [13]:
import numpy as np
from numpy.linalg import matrix_rank

# -------------------------------------------------------
def rowAdd(A,k,l,scale):
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float')
    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

# -------------------------------------------------------
def partialPivoting(M):
    for i in range(0,M.shape[0]-2):
        j=np.argmax(abs(M[i:,i]))
        M[[i,j+i]]=M[[j+i,i]]
    return M

# -------------------------------------------------------   
def forwardElimination(M):
    # ith equation is the pivot equation
    for i in range(0,M.shape[0]-1):
        # Subtracting the pivot equation
        pivot = M[i,i]
        if pivot == 0:
            raise Exception('Pivot is zero')
            
        for j in range(i+1,M.shape[0]):
            M = rowAdd(M,i,j,-M[j,i]/pivot)
    return M

# -------------------------------------------------------
def backSubstitution(M):
    X=np.zeros(M.shape[0])
    for i in range(M.shape[0]-1,-1,-1):
        X[i]=(M[i,-1]-np.dot(M[i,:-1],X))/M[i,i]
        
    return X

# -------------------------------------------------------
def gaussElimination(M):
    if matrix_rank(M) != M.shape[0]:
            raise Exception('System cannot be solved')
    M = partialPivoting(M)
    print('Matrix after partial pivoting:\n',M,'\n')
    M = forwardElimination(M)
    print('Matrix after forward elimination:\n',M,'\n')
    X = backSubstitution(M)
    print('Roots are ',X)
    return X

In [14]:
# Augmented matrix
M=np.array([[0,5,3,1,2],[2,0,1,2,1],[-1,2,0,1,1],[3,4,1,-5,3]])
print('Input matrix:\n',M,'\n')
X = gaussElimination(M)



Input matrix:
 [[ 0  5  3  1  2]
 [ 2  0  1  2  1]
 [-1  2  0  1  1]
 [ 3  4  1 -5  3]] 

Matrix after partial pivoting:
 [[ 3  4  1 -5  3]
 [ 0  5  3  1  2]
 [-1  2  0  1  1]
 [ 2  0  1  2  1]] 

Matrix after forward elimination:
 [[ 3.          4.          1.         -5.          3.        ]
 [ 0.          5.          3.          1.          2.        ]
 [ 0.          0.         -1.66666667 -1.33333333  0.66666667]
 [ 0.          0.          0.          4.32        0.84      ]] 

Roots are  [ 0.58333333  0.69444444 -0.55555556  0.19444444]


In [10]:
M=np.array([[4,3,-5,2],[-2,-4,5,2],[7,8,0,-3],[1,0,2,1],[9,1,-6,6]])
print('Input matrix:\n',M,'\n')
gaussElimination(M)


Input matrix:
 [[ 4  3 -5  2]
 [-2 -4  5  2]
 [ 7  8  0 -3]
 [ 1  0  2  1]
 [ 9  1 -6  6]] 



Exception: System cannot be solved