In [ ]:
#https://towardsdatascience.com/find-the-inverse-of-a-matrix-using-python-3aeb05b48308

In [1]:
import numpy as np

#given matrix
A = np.array([[1,0,1], [0,1,1], [1,1,1]])

def InverseGaussian(A):

        #Check if nxn matrix
        n = A.shape[0]  # m is number of rows in A
        m = A.shape[1]  # n is number of columns in A
        
        #if not nxn matrix, raise flag
        if(m != n):
            raise Exception('Not an nxn matrix')

        #Create identity Matrix
        I = np.identity(n=n)
        #Combine I and A matrix
        M = np.concatenate((A, I), axis = 1)

        for i in range(0, n):
            print("Step: ",i)
            print(M)
                 
            j = 1                                   #initialize row-swap iterator
            pivot = M[i][i]                         #Select pivot value

            #if pivot is zero, remaining rows are all zeros
            if pivot == 0:
                #return inverse matrix
                return M[:,n:]


            while pivot == 0 and i + j < n:         #find next non-zero leading coefficient
                
                M[[i,i + j]] = M[[i + j, i]]        #perform row swap operation
                j+=1                                #increment row-swap iterator
                                                    
                pivot = M[i][i]                     #select (new) pivot


            #extract row
            row = M[i]

            #get 1 along the diagonal
            M[i] = row / pivot

            #iterate over all rows except pivot to get augmented matrix into RREF
            #for j in [k for k in range(0,n) if k != i]:
                #M[j] = M[j] - M[i] * M[j][i]

            #iterate over all rows except pivot to get augmented matrix into RREF
            for j in range(0,n):
                if j!=i:
                    M[j] = M[j] - M[i] * M[j][i]

        #full version
        return M
        #abridged version
        #return M[:, n:]

print("Inverse is: \n", InverseGaussian(A))
#print(np.linalg.inv(A))

Step:  0
[[1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 0. 1.]]
Step:  1
[[ 1.  0.  1.  1.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.]
 [ 0.  1.  0. -1.  0.  1.]]
Step:  2
[[ 1.  0.  1.  1.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.]
 [ 0.  0. -1. -1. -1.  1.]]
Inverse is: 
 [[ 1.  0.  0.  0. -1.  1.]
 [ 0.  1.  0. -1.  0.  1.]
 [-0. -0.  1.  1.  1. -1.]]


In [30]:
import numpy as np

#given matrix
A = np.array([[1,0,1], [0,1,1], [1,1,1]])

def InverseGaussian(A):
    
    n = GetDimension(A)

    #Create identity Matrix
    I = np.identity(n=n)
    
    AugmentedMatrix = np.concatenate((A, I), axis = 1)            #Augmented Matrix Combine I and A matrix

    for i in range(0, n):
        print(" \n Step: ",i)
        print(AugmentedMatrix)

        inverseMatrix = RowOperations(AugmentedMatrix,i, n)

    return inverseMatrix                            #full version
    #abridged version                               #return M[:, n:]
        
def GetDimension(A):
    #Check if nxn matrix
    n = A.shape[0]  # m is number of rows in A
    m = A.shape[1]  # n is number of columns in A
    
    #if not nxn matrix, raise flag
    if(m != n):
        raise Exception('Not an nxn matrix')
    
    return n


def RowOperations(M,i, n):

    j = 1                                       #initialize row-swap iterator
    pivot = M[i][i]                             #Select pivot value

    #if pivot is zero, remaining rows are all zeros
    if pivot == 0:
        return M[:,n:]                          #return inverse matrix

    while pivot == 0 and i + j < n:                 #find next non-zero leading coefficient
        
        M[[i,i + j]] = M[[i + j, i]]                #perform row swap operation
        j+=1                                        #increment row-swap iterator
                                            
        pivot = M[i][i]                             #select (new) pivot

    row = M[i]                                      #extract row
    M[i] = row / pivot                              #get 1 along the diagonal

    #for j in [k for k in range(0,n) if k != i]:                        #iterate over all rows except pivot to get augmented matrix into RREF
        #M[j] = M[j] - M[i] * M[j][i]

    for j in range(0,n):
        if j!=i:
            M[j] = M[j] - M[i] * M[j][i]
            #print('\n Row Operation: ')
            #print(M)
    return M
    #return M[:,n:]


print("\nInverse is: \n", InverseGaussian(A))
#print(np.linalg.inv(A))

 
 Step:  0
[[1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 0. 1.]]
 
 Step:  1
[[ 1.  0.  1.  1.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.]
 [ 0.  1.  0. -1.  0.  1.]]
 
 Step:  2
[[ 1.  0.  1.  1.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.]
 [ 0.  0. -1. -1. -1.  1.]]

Inverse is: 
 [[ 1.  0.  0.  0. -1.  1.]
 [ 0.  1.  0. -1.  0.  1.]
 [-0. -0.  1.  1.  1. -1.]]


In [29]:
import numpy as np

#given matrix
A = np.array([[1,0,1], [0,1,1], [1,1,1]])

def InverseGaussian(A):
    
    n = GetDimension(A)
    I = np.identity(n=n)                                          #Create identity Matrix
    
    AugmentedMatrix = np.concatenate((A, I), axis = 1)            #Augmented Matrix Combine I and A matrix

    for i in range(0, n):
        inverseMatrix = RowOperations(AugmentedMatrix,i, n)

    return inverseMatrix                                            #full version

        
def GetDimension(A):
                                                            #Check if nxn matrix
    n = A.shape[0]                                          # m is number of rows in A
    m = A.shape[1]                                          # n is number of columns in A
    
    if(m != n):                                             #if not nxn matrix, raise flag
        raise Exception('Not an nxn matrix')
    
    return n


def RowOperations(M,i, n):

    j = 1                                           #initialize row-swap iterator
    pivot = M[i][i]                                 #Select pivot value

    #if pivot is zero, remaining rows are all zeros
    if pivot == 0:
        return M[:,n:]                              #return matrix

    while pivot == 0 and i + j < n:                 #find next non-zero leading coefficient
        
        M[[i,i + j]] = M[[i + j, i]]                #perform row swap operation
        j+=1                                        #increment row-swap iterator
                                            
        pivot = M[i][i]                             #select (new) pivot

    row = M[i]                                      #extract row
    M[i] = row / pivot                              #get 1 along the diagonal

    for j in range(0,n):
        if j!=i:
            M[j] = M[j] - M[i] * M[j][i]

    return M[:,n:]


print("\nInverse is: \n", InverseGaussian(A))
#print(np.linalg.inv(A))


Inverse is: 
 [[ 0. -1.  1.]
 [-1.  0.  1.]
 [ 1.  1. -1.]]
