In [ ]:
#https://towardsdatascience.com/find-the-inverse-of-a-matrix-using-python-3aeb05b4830

In [31]:
import numpy as np

#given matrix
A = np.array([[1,0,1], [0,1,1], [1,1,1]])

def InverseGaussian(A):

        #Check if nxn matrix
        m = A.shape[0]  # m is number of rows in A
        n = A.shape[1]  # n is number of columns in A
        
        #if not nxn matrix, raise flag
        if(m != n):
            raise Exception('Not an nxn matrix')

        #Create identity Matrix
        I = np.identity(n=n)
        #Combine I and A matrix
        M = np.concatenate((A, I), axis = 1)

        print(M)

        for i in range(0, n):
            #initialize row-swap iterator
            j = 1
            #Select pivot value
            pivot = M[i][i]

            #find next non-zero leading coefficient
            while pivot == 0 and i + j < n:
                #perform row swap operation
                M[[i,i + j]] = M[[i + j, i]]
            #increment row-swap iterator
                j+=1
            #get new pivot
                pivot = M[i][i]

            #if pivot is zero, remaining rows are all zeros
            if pivot == 0:
                #return inverse matrix
                return M[:,n:]

            #extract row
            row = M[i]

            #get 1 along the diagonal
            M[i] = row / pivot

            #iterate over all rows except pivot to get augmented matrix into RREF
            for j in [k for k in range(0,n) if k != i]:
                M[j] = M[j] - M[i] * M[j][i]

        #inverse = 

        #full version
        return M
        #abridged version
        #return M[:, n:]
        
print(InverseGaussian(A))

[[1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 0. 1.]]
[[ 1.  0.  0.  0. -1.  1.]
 [ 0.  1.  0. -1.  0.  1.]
 [-0. -0.  1.  1.  1. -1.]]
